"""Added teacher_name column in mark model

Revision ID: 447a3ba84036
Revises: 7c8891a0588e
Create Date: 2025-06-23 19:22:39.180566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '447a3ba84036'
down_revision = '7c8891a0588e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mark', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_name', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mark', schema=None) as batch_op:
        batch_op.drop_column('teacher_name')

    # ### end Alembic commands ###
