"""Modifying column is_pdf in Timetable Model

Revision ID: 85e78010907c
Revises: 17566368d973
Create Date: 2025-06-26 18:32:48.183205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85e78010907c'
down_revision = '17566368d973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timetable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_pdf', sa.Boolean(), nullable=True))
        batch_op.drop_column('id_pdf')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timetable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_pdf', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('is_pdf')

    # ### end Alembic commands ###
