from .user_model import User
from .batch_model import Batch
from .mark_model import Mark
from .fee_model import Fee
from .teacher_batch_model import teacher_batch
from .timetable_model import Timetable
from .leave_model import LeaveRequest
from .notice_model import Notice
from .attendance_model import Attendance